# Generated by Django 4.1.5 on 2023-01-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_doors_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Tiptronic', 'Tiptronic'), ('CVT', 'CVT'), ('Robotic', 'Robotic')], max_length=10),
        ),
    ]
