# Generated by Django 4.1.5 on 2023-01-19 08:56

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
